### ISSUE TITLE
Crash when attempting to open a connection

### ISSUE THREAD

**Issue by FineTralfazz** [xseignard/cordovarduino#65]
When I try to open a serial connection with `serial.open({baudRate:57600}, sCallback, eCallback)`, the entire app crashes. This is the error it prints to the ADB log:
```
08-03 06:01:27.594 28970 29027 D Serial  : Action: openSerial
08-03 06:01:27.601 28970 29000 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
08-03 06:01:27.601 28970 29000 E AndroidRuntime: Process: io.cordova.hellocordova, PID: 28970
08-03 06:01:27.601 28970 29000 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'android.hardware.usb.UsbDevice com.hoho.android.usbserial.driver.UsbSerialDriver.getDevice()' on a null object reference
08-03 06:01:27.601 28970 29000 E AndroidRuntime: 	at fr.drangies.cordova.serial.Serial$3.run(Serial.java:226)
08-03 06:01:27.601 28970 29000 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-03 06:01:27.601 28970 29000 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-03 06:01:27.601 28970 29000 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
08-03 06:01:27.607   858  3262 W ActivityManager:   Force finishing activity io.cordova.hellocordova/.MainActivity
```
Any ideas?

**Comment by xseignard** [comment]
Code and device please...

**Comment by FineTralfazz** [comment]
Nexus 5X running 6.0.1. I can reproduce the crash with the default project and only that line of code and the callbacks (which only contain console.logs) in index.js.

**Comment by xseignard** [comment]
Well, is it a clone or an official Arduino?

And are you sure of your USB cable?

**Comment by xseignard** [comment]
I have a Nexus 5, and everything is fine with an Arduino mega

**Comment by FineTralfazz** [comment]
It is a clone, but it works fine with multiple other computers and with [a native serial terminal app I found](https://play.google.com/store/apps/details?id=jp.ksksue.app.terminal&hl=en), so I don't think it's a hardware issue. But if it's working for you, clearly it's _something_ on my end... I'll keep experimenting with it and see if I can figure anything out.

**Comment by xseignard** [comment]
What is its vid/pid?

**Comment by FineTralfazz** [comment]
VID: 2341
PID: 0042

**Comment by xseignard** [comment]
Have you tried this: https://github.com/xseignard/cordovarduino#your-device-is-not-yet-known ?

**Comment by gregor-srdic** [comment]
@FineTralfazz have you found any solution? I have the same problem with my Galaxy S6 with Android 6.0.1.
It happens even if nothing is connected to the USB port.

`01-13 15:26:53.831 7781-7848/eu.seltron.mobilebootloader E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-3
 Process: eu.seltron.mobilebootloader, PID: 7781
 java.lang.NullPointerException: Attempt to invoke interface method 'android.hardware.usb.UsbDevice com.hoho.android.usbserial.driver.UsbSerialDriver.getDevice()' on a null object reference
     at fr.drangies.cordova.serial.Serial$3.run(Serial.java:227)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
     at java.lang.Thread.run(Thread.java:818)
01-13 15:26:53.881 3467-7914/? E/android.os.Debug: ro.product_ship = true
01-13 15:26:53.881 3467-7914/? E/android.os.Debug: ro.debug_level = 0x4f4c
01-13 15:26:53.881 3467-7914/? E/android.os.Debug: sys.mobilecare.preload = false
`

**Comment by xseignard** [comment]
VID? PID?

**Comment by gregor-srdic** [comment]
Thanks for your response, my mistake was calling serial.open without serial.requestPermission. However, the latter returns "No device found", I have to research this :)

VID = 1240;
PID = 60;

**Comment by gregor-srdic** [comment]
i managed to get past the requestPermission but now I face the following problem:

I am trying to develop a firmware update application for Microchip controller.
I can open serial connection to the device in normal mode {vid: '04d8', pid: '000A'}, while in bootloader mode { vid: '04d8', pid: '003c' } the serial.requestPermission works, but serial.open crashes the application with 
`java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
at android.hardware.usb.UsbDevice.getInterface(UsbDevice.java:244)
at com.hoho.android.usbserial.driver.CdcAcmSerialDriver$CdcAcmSerialPort.open(CdcAcmSerialDriver.java:122)
at fr.drangies.cordova.serial.Serial$3.run(Serial.java:242)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818
`

**Comment by gregor-srdic** [comment]
after more research i discovered that in bootloader mode, my device is acting like an HID device, does that mean this plugin will not work?

**Comment by kevpogo** [comment]
Hello all !

I've the same problem, and the same error than @gregor-srdic : I've a HID device and I've the java.lang.ArrayIndexOutOfBoundsException: length=1; index=1.
Have you find the solution ?

**Comment by FilipMatys** [comment]
Hi there,

I am facing the same issue with Thermal Printer Rongta RP80-WUE. It uses the classic USB-to-printer cable.

```
VID: 4070
PID: 33054
```

When using no driver, the app crashes with:
```
D/Serial  ( 3029): Action: requestPermission
D/UsbBroadcastReceiver( 3029): Permission to connect to the device was accepted!
D/Serial  ( 3029): Action: openSerial
D/CdcAcmSerialDriver( 3029): claiming interfaces, count=1
D/CdcAcmSerialDriver( 3029): Control iface=UsbInterface[mId=0,mClass=7,mSubclass=1,mProtocol=2,mEndpoints=[Landroid.os.Parcelable;@41bfd570]
D/CdcAcmSerialDriver( 3029): Control endpoint direction: 128
D/CdcAcmSerialDriver( 3029): Claiming data interface.
W/dalvikvm( 3029): threadid=33: thread exiting with uncaught exception (group=0x4176a2a0)
E/AndroidRuntime( 3029): FATAL EXCEPTION: pool-1-thread-3
E/AndroidRuntime( 3029): Process: kasamax.mobile, PID: 3029
E/AndroidRuntime( 3029): java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
E/AndroidRuntime( 3029):        at android.hardware.usb.UsbDevice.getInterface(UsbDevice.java:155)
E/AndroidRuntime( 3029):        at com.hoho.android.usbserial.driver.CdcAcmSerialDriver$CdcAcmSerialPort.open(CdcAcmSerialDriver.java:122)
E/AndroidRuntime( 3029):        at fr.drangies.cordova.serial.Serial$3.run(Serial.java:242)
E/AndroidRuntime( 3029):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 3029):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 3029):        at java.lang.Thread.run(Thread.java:841)
```

When using FTDI driver, it comes with:
```
D/Serial  ( 3752): Action: requestPermission
D/UsbBroadcastReceiver( 3752): Permission to connect to the device was accepted!
D/Serial  ( 3752): Action: openSerial
D/FtdiSerialDriver( 3752): claimInterface 0 SUCCESS
D/UsbDeviceConnectionJNI( 3752): close
D/Serial  ( 3752): Reset failed: result=-1
D/Serial  ( 3752): Serial port opened!
W/CordovaPlugin( 3752): Attempted to send a second callback for ID: Serial118814763
W/CordovaPlugin( 3752): Result was: "Serial port opened!"
I/Serial  ( 3752): Starting io manager.
I/SerialInputOutputManager( 3752): Running ..
W/SerialInputOutputManager( 3752): Run ending due to exception: null
W/SerialInputOutputManager( 3752): java.lang.NullPointerException
W/SerialInputOutputManager( 3752):      at com.hoho.android.usbserial.driver.FtdiSerialDriver$FtdiSerialPort.read(FtdiSerialDriver.java:315)
W/SerialInputOutputManager( 3752):      at com.hoho.android.usbserial.util.SerialInputOutputManager.step(SerialInputOutputManager.java:159)
W/SerialInputOutputManager( 3752):      at com.hoho.android.usbserial.util.SerialInputOutputManager.run(SerialInputOutputManager.java:141)
W/SerialInputOutputManager( 3752):      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/SerialInputOutputManager( 3752):      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/SerialInputOutputManager( 3752):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/SerialInputOutputManager( 3752):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/SerialInputOutputManager( 3752):      at java.lang.Thread.run(Thread.java:841)
```

Opening the connection with this settings:
https://postorg.com.ua/published/file/Rongta/Driver%20Setup%20Manual.pdf#page=8

Like so:
{
    baudRate: 19200
}

To be honest, not sure whether I am using the proper driver oO.

Thank you
Filip

**Comment by FilipMatys** [comment]
So I made it work. To avoid the same frustration I have been through, here is how I did it:

I had to download this library:
https://github.com/mik3y/usb-serial-for-android

It is the one this plugin is dependent on. Unfortunately, the library in this plugin is quite old and expects the device to have multiple interfaces. New version of the library does not.

I used this fork, which uses raw files, not library:
https://github.com/r1000ru/cordovarduino

I removed obsolete files from config.xml (like example files) and copied the new library into that fork. Watch for proper paths!

Still, it was not enough :) But it might be for you.

I went through the driver code and found out it required both read and write endpoints. And that was the reason, why connection with my printer could not be opened. I modified the driver to not require 3 endpoints and to not throw exception when there is no read endpoint.

And thank the Almighty whoever that is, it works now.

**Comment by deysudip** [comment]
@FilipMatys,
Thank you for showing me some ray of hope? One question, How to change the driver file the way you did? I am using an MTP pos printer and having the same issue.

**Comment by deysudip** [comment]
@FilipMatys,
I almost got your solution. I checked out the fork you mentioned. And also did the changes to exclude the read endpoint (As far as I could). 
But being a noob in java development, I got stuck in the following 

`I removed obsolete files from config.xml (like example files) and copied the new library into that fork. Watch for proper paths!`

which config.xml you are talking about? I can see the example files though. And which path I should watch for?

Please help and make my day  :smiley:

**Comment by FilipMatys** [comment]
Sorry for the delay ^^. I do not have my work computer with me right now, so my answer might be a little limited.

I think I meant plugin.xml, not config.xml. You have to set proper paths to the https://github.com/mik3y/usb-serial-for-android library you downloaded. I think those are the only paths to look for. There might be some other, like test/something, so remove these as those are not needed.

**Comment by deysudip** [comment]
@FilipMatys,
Yes buddy, I got that by now. I have also done a test build for the app. Now making the changes for not considering read endpoint. Hopefully, I will get it right.

Keeping my finger crossed. :crossed_fingers:

**Comment by deysudip** [comment]
@FilipMatys, Hello Again.
I am now able to ask for permission and subsequently connect with the printer without and error.
But facing an issue while writing. Every time it is showing me that write failed.
Did you change anything in the write() part? 
And which driver you use to connect the printer?

I used the CdcAcmSerialDriver for requesting.
And my config is: 
      baudRate: 19200,
      dataBits: 8,
      stopBits: 1,
      parity: 0,
      dtr: true,
      rts: true,
      sleepOnPause: false

Also, I have a weird problem. I also tried to use the apk provided with the printer. It is perfectly printing whatever input I am giving. And then keeping the printer on, coming back to my app and again doing request, open and write, now my app also is writing perfectly.

But if I restart the printer and directly go to my app and try to request, open and write, then write fails.

I could not fathom what is happening. I tried to compare the seller provided apk to look for an escpos command which I may have missed, but found nothing. 

Can you help me with the issue?

**Comment by deysudip** [comment]
Found the issue, there are some steps in setParameters(), which is causing the issue. Moreover, my printer did not need it. So I commented this out and now everything is working fine.

**Comment by xseignard** [comment]
@FilipMatys @r1000ru I can update the usbseriallibrary in this repo, could you tell me about any modifications you did on it (if there is any) ?

@deysudip could you sum up what you did exactly to make the plugin work ? for documentation purposes

thanks
regards

**Comment by deysudip** [comment]
Sure, I will sum it up over the weekend. Little busy on the work right now. Sorry for the delay.

STEP 1: I have copied the latest [usb-serial-for-android](https://github.com/mik3y/usb-serial-for-android) lib into your plugin.

STEP 2: For single interface device the above lib expects all the 3 endpoints (Control, Read & Write) to present, or to throw an exception. I changed the logic a bit and removed the exception here. Instead, I add the exception at the respective functions like in read() or write() method. So, when a user wants to write something to the serial device, if the corresponding endpoint is not found previously it will throw an error.

I found my printer has read and write endpoint only. I can't be sure though.

STEP 3: I have added a step in your serial.java `requestPermission()` method, so if the user is not providing any hardcoded vid or pid in the ionic code, it will get the vid and pid of attached devices via `UsbManager.getDeviceList()` and will use the CdcAcmSerialDriver by default to try and connect to the device. I assumed that the user will attach only one device.

STEP 4: Also, I was having an issue while trying to print through the printer. In `openSerial()` method, it is calling `port.setParameters(baudRate, dataBits, stopBits, parity)`, which has a method to `transferControl` with some data. It seems that performing this method while opening the connection is prohibiting me to write anything through the printer. So, I have commented out this step. And now, it performs okay with the writing method. So, I continued with this. Maybe I needed another call to `transferControl()` method to make the printer ready for printing. I did not understand this part fully, and it was mostly trial and error.
But as the `open()` method of your plugin is expecting an object to pass as a parameter, I have to provide it with  `open({baudRate: 9600})` to connect.
I suppose you could change the `open()` method to make that parameter optional and if none is provided you could also skip the `port.setParameter()` method in your serial.java.

This is a roughly the workarounds I applied to connect my printer through your plug in.

Any advice is most welcome.

**Comment by steffanhalv** [comment]
@deysudip Can you please share your code anyway? It would be really helpful.

**Comment by teamapex1** [comment]
Hi @deysudip I followed you procedure. But still it gives me
 java.lang.ArrayIndexOutOfBoundsException: length=0; index=1 at android.hardware.usb.UsbInterface.getEndpoint(UsbInterface.java:135) at com.hoho.android.usbserial.driver.CdcAcmSerialDriver$CdcAcmSerialPort.open(CdcAcmSerialDriver.java:129) at fr.drangies.cordova.serial.Serial$3.run(Serial.java:242) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) at java.lang.Thread.run(Thread.java:760)

**Comment by Jeremy38100** [comment]
@xseignard did you update the usbseriallibrary in this repo ?

**Comment by singhnar** [comment]
@deysudip - Can you please share your code? I am also facing similar issue with opening the connection.
